### ISSUE TITLE
Redeclared class error

### ISSUE THREAD

**Issue by vernard** [MageTest/MageSpec#54] opened 2014-07-07 05:13 UTC
I followed the basic usage part in the README. It was nice and clear until i run "bin/phpspec run". It showed this error:

PHP Fatal error:  Cannot redeclare class spec\Magespec_Reviews_Model_ProductSpec in /var/ww
w/Spec\htdocs\app\code\local\Magespec\Reviews\Model\ProductSpec.php on line 14

I'm using the version 2.0.0. Error still exists when I changed the version to "dev-develop".

Please help.

**Comment by maxbaldanza** [comment] 2017-07-28 15:33
Hi @vernard,
I know this is a fairly old PR but by chance were you using an windows environment with magespec?
I've just tried the steps to create the error on the latest version [4.0.0](https://github.com/MageTest/MageSpec/releases/tag/4.0.0) and can't reproduce but I believe this is may be a windows related looking at the `D:\Projects` path.
I'm closing in this favour of https://github.com/MageTest/MageSpec/issues/155

Feel free to re-open if this is not the case.

**Closed by maxbaldanza** 2017-07-28 15:33 UTC

**Comment by vernard** [comment] 2017-07-28 15:36
Right, I was on Windows environment.

Thank you for cleaning this repo.

**Comment by maxbaldanza** [comment] 2017-07-28 15:38
No problem 👍  sorry for the late reply.
There's a few issues on windows which would be good to get fixed up: https://ci.appveyor.com/project/maxbaldanza/magespec
Happy to accept any PR's if you'd like to contribute towards it 👍
